### ISSUE TITLE
Blynk 

### ISSUE THREAD

**Issue by LuisDiazUgena** [MikeMitterer/cpp-sonoff#1]
Hi! I've found your repo while searching for blynk examples for the sonoff s20 but while reading the code there is nothing. Have you developed something more?

Thanks!

**Comment by MikeMitterer** [comment]
The idea was to provide a "sonoff-hello-world" - so thats all :-)
But in the next few days I'll add an Alexa-Sample - so stay tuned. I'll send you a link to the new repo

**Comment by MikeMitterer** [comment]
Here is the Alexa-Version: https://github.com/MikeMitterer/cpp-alexa
